export const weatherMapping: Record<number, { description: string }> = {
  0: { description: 'Clear sky' },
  1: { description: 'Mainly clear' },
  2: { description: 'Partly cloudy' },
  3: { description: 'Overcast' },
  45: { description: 'Fog' },
  48: { description: 'Depositing rime fog' },
  51: { description: 'Drizzle light' },
  53: { description: 'Drizzle moderate' },
  55: { description: 'Drizzle dense' },
  56: { description: 'Freezing drizzle light' },
  57: { description: 'Freezing drizzle dense' },
  61: { description: 'Rain slight' },
  63: { description: 'Rain moderate' },
  65: { description: 'Rain heavy' },
  66: { description: 'Freezing rain light' },
  67: { description: 'Freezing rain heavy' },
  71: { description: 'Snow slight' },
  73: { description: 'Snow moderate' },
  75: { description: 'Snow heavy' },
  77: { description: 'Snow grains' },
  80: { description: 'Rain showers slight' },
  81: { description: 'Rain showers moderate' },
  82: { description: 'Rain showers violent' },
  85: { description: 'Snow showers slight' },
  86: { description: 'Snow showers heavy' },
  95: { description: 'Thunderstorm' },
  96: { description: 'Thunderstorm with hail' },
  99: { description: 'Thunderstorm heavy hail' },
};
